name: CI/CD Pipeline for Laundry App

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Build Node.js app
        run: npm run build || echo "No build step found, skipping..."

      - name: Build Docker image
        run: docker build -t laundry-app:latest .

      # Langkah opsional: push ke Docker Hub
      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Push Docker image
        if: github.ref == 'refs/heads/main'
        run: |
          docker tag laundry-app:latest ${{ secrets.DOCKERHUB_USERNAME }}/laundry-app:latest
          docker push ${{ secrets.DOCKERHUB_USERNAME }}/laundry-app:latest